In [9]:
import pickle
import pandas as pd
from IPython.display import display

pd.options.display.max_columns = None

%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt

import numpy as np
np.random.seed(42)

In [10]:
df = pickle.load(open('data.pkl', 'rb'))
df.head()

,horse_rating,horse_total_races,horse_total_wins,jockey_num_1_place,jockey_num_2_place,jockey_num_3_place,jockey_num_4_below,jockey_num_dirt_races,jockey_num_dirt_wins,jockey_num_turf_races,jockey_num_turf_wins,jockey_place_1_or_2_rate,jockey_place_1_rate,jockey_place_any_rate,jockey_sum_earnings,direction,distance,finish_time,odds,horse_age,horse_sex,horse_url,horse_weight,jockey_url,order_of_finish,participant_count,popularity,post_position,date,location,race_url,track_condition,track_type,trainer_url,weather,weight_carried,trainer_num_1_place,trainer_num_2_place,trainer_num_3_place,trainer_num_4_below,trainer_num_dirt_races,trainer_num_dirt_wins,trainer_num_turf_races,trainer_num_turf_wins,trainer_place_1_or_2_rate,trainer_place_1_rate,trainer_place_any_rate,trainer_sum_earnings
0,NaN,3,0,244.0,232.0,226.0,2734,1709.0,125.0,1727.0,119.0,0.139,0.071,0.204,375143.7,right,1400,89.6,1.0,2,male,http://db.netkeiba.com/horse/2016101845/,442(-4),http://db.netkeiba.com/jockey/result/01154,12,12,12,6,2018-10-02,hanshin,http://db.netkeiba.com/race/201809040901/,slightly_heavy,dirt,http://db.netkeiba.com/trainer/result/01110/,sunny,54.0,196.0,166.0,189.0,2151.0,856.0,51.0,1800.0,141.0,0.134,0.073,0.204,513245.6
1,NaN,18,2,135.0,150.0,156.0,1824,1134.0,70.0,1131.0,65.0,0.126,0.060,0.195,225635.6,right,1800,115.9,2.0,5,castrated,http://db.netkeiba.com/horse/2013105140/,514(+4),http://db.netkeiba.com/jockey/result/01157,15,15,14,3,2018-10-02,hanshin,http://db.netkeiba.com/race/201809040912/,slightly_heavy,dirt,http://db.netkeiba.com/trainer/result/01123/,cloudy,57.0,118.0,131.0,139.0,1561.0,997.0,60.0,915.0,51.0,0.128,0.061,0.199,220845.8
2,3.25,45,5,321.0,372.0,432.0,6175,3718.0,172.0,3582.0,149.0,0.095,0.044,0.154,700642.1,right,1600,95.9,2.0,8,male,http://db.netkeiba.com/horse/2010100356/,502(-4),http://db.netkeiba.com/jockey/result/01034,7,7,6,1,2018-10-02,hanshin,http://db.netkeiba.com/race/201809040911/,good,turf,http://db.netkeiba.com/trainer/result/01161/,cloudy,58.0,8.0,11.0,9.0,112.0,51.0,3.0,86.0,5.0,0.136,0.057,0.200,16313.6
3,NaN,28,4,321.0,372.0,432.0,6175,3718.0,172.0,3582.0,149.0,0.095,0.044,0.154,700642.1,right,1200,70.8,4.0,7,male,http://db.netkeiba.com/horse/2011100215/,482(+4),http://db.netkeiba.com/jockey/result/01034,9,9,9,3,2018-10-02,hanshin,http://db.netkeiba.com/race/201809040910/,good,turf,http://db.netkeiba.com/trainer/result/01090/,cloudy,57.0,121.0,143.0,153.0,2466.0,1587.0,70.0,1207.0,46.0,0.092,0.042,0.145,216111.3
4,NaN,37,3,210.0,232.0,220.0,4273,2492.0,113.0,2443.0,97.0,0.090,0.043,0.134,378464.8,right,2400,149.5,1.0,7,male,http://db.netkeiba.com/horse/2011103629/,468(+2),http://db.netkeiba.com/jockey/result/01130,8,8,8,6,2018-10-02,hanshin,http://db.netkeiba.com/race/201809040909/,good,turf,http://db.netkeiba.com/trainer/result/01101/,sunny,52.0,204.0,229.0,203.0,2221.0,1652.0,145.0,1198.0,59.0,0.152,0.071,0.223,372508.3

In [11]:
df.describe()

,horse_rating,horse_total_races,horse_total_wins,jockey_num_1_place,jockey_num_2_place,jockey_num_3_place,jockey_num_4_below,jockey_num_dirt_races,jockey_num_dirt_wins,jockey_num_turf_races,jockey_num_turf_wins,jockey_place_1_or_2_rate,jockey_place_1_rate,jockey_place_any_rate,jockey_sum_earnings,distance,finish_time,odds,horse_age,participant_count,popularity,post_position,weight_carried,trainer_num_1_place,trainer_num_2_place,trainer_num_3_place,trainer_num_4_below,trainer_num_dirt_races,trainer_num_dirt_wins,trainer_num_turf_races,trainer_num_turf_wins,trainer_place_1_or_2_rate,trainer_place_1_rate,trainer_place_any_rate,trainer_sum_earnings
count,95870.000000,229351.000000,229351.000000,228945.000000,229109.000000,229127.000000,229351.000000,229303.000000,228613.000000,229340.000000,228462.000000,229148.000000,228945.000000,229214.000000,2.292720e+05,229351.000000,229351.000000,229351.000000,229351.000000,229351.000000,229351.000000,229351.000000,229351.000000,229047.000000,229073.000000,229096.000000,229350.000000,229260.000000,228953.000000,229347.000000,229040.000000,229105.000000,229047.000000,229139.000000,2.291600e+05
mean,2.967876,25.563455,2.637486,669.034720,646.104435,629.725615,5929.497364,3849.179217,329.370591,3984.220947,337.369195,0.142866,0.071884,0.214038,1.313486e+06,1646.488116,102.167559,3.402566,3.647963,14.842878,7.889322,4.739460,55.002531,318.165756,310.905004,304.106471,3083.171171,1899.263853,150.039724,1997.648890,157.542159,0.150254,0.075694,0.223596,6.272210e+05
std,0.580862,16.933723,2.388540,715.519954,614.168283,548.927147,3949.494718,2668.381234,340.390421,2985.054827,380.572540,0.066477,0.039415,0.086095,1.474667e+06,419.239618,29.110020,2.422794,1.344820,2.305092,4.462248,2.272844,1.780623,216.831677,189.859916,173.308975,1466.004149,892.204787,89.411503,1151.764872,136.234688,0.042856,0.026127,0.054688,4.994469e+05
min,0.860000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.017000,0.006000,0.017000,5.000000e+01,2.000000,53.800000,1.000000,2.000000,5.000000,1.000000,1.000000,47.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.008000,0.007000,0.007000,1.000000e+02
25%,2.500000,13.000000,1.000000,131.000000,142.000000,156.000000,2193.000000,1466.000000,69.000000,1145.000000,51.000000,0.095000,0.044000,0.150000,2.250444e+05,1400.000000,81.100000,1.000000,3.000000,14.000000,4.000000,3.000000,54.000000,162.000000,164.000000,166.000000,2010.000000,1217.000000,81.000000,1131.000000,64.000000,0.122000,0.059000,0.188000,2.850378e+05
50%,3.000000,23.000000,2.000000,449.000000,527.000000,532.000000,5826.000000,3633.000000,240.000000,3824.000000,223.000000,0.126000,0.064000,0.197000,8.945516e+05,1600.000000,99.300000,3.000000,3.000000,16.000000,8.000000,5.000000,55.000000,269.000000,267.000000,279.000000,2972.000000,1943.000000,138.000000,1853.000000,114.000000,0.147000,0.072000,0.221000,4.788483e+05
75%,3.400000,34.000000,4.000000,926.000000,918.000000,927.000000,8163.000000,5379.000000,474.000000,5311.000000,478.000000,0.163000,0.082000,0.251000,1.837582e+06,1800.000000,116.500000,5.000000,4.000000,16.000000,11.000000,7.000000,56.000000,472.000000,435.000000,430.000000,4328.000000,2533.000000,207.000000,2615.000000,205.000000,0.173000,0.090000,0.253000,8.581950e+05
max,4.700000,172.000000,32.000000,4010.000000,2972.000000,2394.000000,14844.000000,9838.000000,1855.000000,11460.000000,2155.000000,0.507000,0.336000,0.614000,8.367161e+06,4250.000000,302.000000,9.000000,12.000000,18.000000,18.000000,8.000000,64.000000,1427.000000,1040.000000,861.000000,8108.000000,4165.000000,418.000000,5968.000000,1002.000000,0.500000,0.500000,1.000000,3.376531e+06

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 229351 entries, 0 to 229350
Data columns (total 48 columns):
horse_rating                 95870 non-null float64
horse_total_races            229351 non-null int64
horse_total_wins             229351 non-null int64
jockey_num_1_place           228945 non-null float64
jockey_num_2_place           229109 non-null float64
jockey_num_3_place           229127 non-null float64
jockey_num_4_below           229351 non-null int64
jockey_num_dirt_races        229303 non-null float64
jockey_num_dirt_wins         228613 non-null float64
jockey_num_turf_races        229340 non-null float64
jockey_num_turf_wins         228462 non-null float64
jockey_place_1_or_2_rate     229148 non-null float64
jockey_place_1_rate          228945 non-null float64
jockey_place_any_rate        229214 non-null float64
jockey_sum_earnings          229272 non-null float64
direction                    222393 non-null object
distance                     229351 non-null int64
finish_time                  229351 non-null float64
odds                         229351 non-null float64
horse_age                    229351 non-null int64
horse_sex                    229351 non-null object
horse_url                    229351 non-null object
horse_weight                 229351 non-null object
jockey_url                   229351 non-null object
order_of_finish              229351 non-null object
participant_count            229351 non-null int64
popularity                   229351 non-null int64
post_position                229351 non-null int64
date                         229351 non-null object
location                     229351 non-null object
race_url                     229351 non-null object
track_condition              229351 non-null object
track_type                   229351 non-null object
trainer_url                  229351 non-null object
weather                      221058 non-null object
weight_carried               229351 non-null float64
trainer_num_1_place          229047 non-null float64
trainer_num_2_place          229073 non-null float64
trainer_num_3_place          229096 non-null float64
trainer_num_4_below          229350 non-null float64
trainer_num_dirt_races       229260 non-null float64
trainer_num_dirt_wins        228953 non-null float64
trainer_num_turf_races       229347 non-null float64
trainer_num_turf_wins        229040 non-null float64
trainer_place_1_or_2_rate    229105 non-null float64
trainer_place_1_rate         229047 non-null float64
trainer_place_any_rate       229139 non-null float64
trainer_sum_earnings         229160 non-null float64
dtypes: float64(27), int64(8), object(13)
memory usage: 85.7+ MB

In [13]:
# x horse_rating (too many blank values)
# o horse_total_races (as-is)
# o horse_total_wins (as-is)
# o jockey_num_1_place (NaN -> 0)
# o jockey_num_2_place (NaN -> 0)
# o jockey_num_3_place (NaN -> 0)
# o jockey_num_4_below (NaN -> 0)
# o jockey_num_dirt_races (NaN -> 0)
# o jockey_num_dirt_wins (NaN -> 0)
# o jockey_num_turf_races (NaN -> 0)
# (!) You may want to drop rows in which the jockey hasn't competed in any dirt or turf races
# o jockey_num_turf_wins (NaN -> 0)
# o jockey_place_1_or_2_rate (NaN -> 0)
# o jockey_place_1_rate (NaN -> 0)
# o jockey_place_any_rate (NaN -> 0)
# o jockey_sum_earnings (NaN -> 0)
# o direction (null values are always '障芝 ダート', check race_url for examples)
# o distance (there are 53 instances where distance=2. It should be 3600m. check race_url pages for example)
# o finish_time (as-is)
# x odds (you screwed up the float parsing logic. you need to recrawl)
# o horse_age (as-is)
# o horse_sex (as-is)
# x horse_url (for debugging only)
# o horse_weight (needs extra parsing. add feature 'weight_diff')
# x jockey_url (for debugging only)
# o order_of_finish (values with strings should be looked into)
# o participant_count (as-is)
# o popularity (as-is)
# o post_position (as-is)
# x date (for debugging only)
# o location (convert to one-hot)
# x race_url (for debugging only)
# ? track_condition ?? see 'direction'
# ? track_type ?? is it accurate?
# x trainer_url (for debugging only)
# o weather (null values seems to all be "小雨" because you didn't check for that pattern. so, default to rainy)
# o weight_carried (as-is)
# o trainer_num_1_place (NaN -> 0)
# o trainer_num_2_place (NaN -> 0)
# o trainer_num_3_place (NaN -> 0)
# o trainer_num_4_below (NaN -> 0)
# o trainer_num_dirt_races (NaN -> 0)
# o trainer_num_dirt_wins (NaN -> 0)
# o trainer_num_turf_races (NaN -> 0)
# o trainer_num_turf_wins (NaN -> 0)
# o trainer_place_1_or_2_rate (NaN -> 0)
# o trainer_place_1_rate (NaN -> 0)
# o trainer_place_any_rate (NaN -> 0)
# o trainer_sum_earnings (NaN -> 0)

# PIPELINE
# feature scaling for numeric values
# one hot conversion for categorical features

In [16]:
from sklearn.model_selection import StratifiedShuffleSplit

# you should clean up null values etc.. before doing stratified split
# also this forces you to think of what you want your label to be!
# sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
# for train_index, test_index in sss.split(df)